"""init tables

Revision ID: ffe2cbe476ed
Revises: 
Create Date: 2025-02-01 17:57:41.257891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffe2cbe476ed'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('hours', sa.Float(), nullable=False),
    sa.Column('project', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checkins_id'), 'checkins', ['id'], unique=False)
    op.create_index(op.f('ix_checkins_project'), 'checkins', ['project'], unique=False)
    op.create_index(op.f('ix_checkins_timestamp'), 'checkins', ['timestamp'], unique=False)
    op.create_index(op.f('ix_checkins_user'), 'checkins', ['user'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_checkins_user'), table_name='checkins')
    op.drop_index(op.f('ix_checkins_timestamp'), table_name='checkins')
    op.drop_index(op.f('ix_checkins_project'), table_name='checkins')
    op.drop_index(op.f('ix_checkins_id'), table_name='checkins')
    op.drop_table('checkins')
    # ### end Alembic commands ###
