version: '3'

tasks:
  default:
    desc: Build and start Docker containers
    cmds:
      - docker compose up -d
  
  clean:
    desc: Remove containers
    cmds:
      - docker compose down

  generate-migrations:
    desc: Generate migrations
    dir: ./api
    cmds:
      - uv run alembic revision --autogenerate -m {{.CLI_ARGS}}

  migrate:
    desc: Run database migrations
    dir: ./api
    cmds:
      - uv run alembic upgrade head

  api-dev:
    desc: Run API in development mode
    dir: ./api
    cmds:
      - uv run fastapi dev src/main.py --reload